### ISSUE TITLE
More permissive license?

### ISSUE THREAD

**Issue by thejohnfreeman** [tools4j/groovy-tables#3]
Wish I could use this at my company, but can't if it's GPL. Have you considered a more permissive license, e.g. MIT?

**Comment by benjwarner** [comment]
Hi John,
That's fine with me.

I'll change over to MIT license this weekend.

Cheers,
Ben




On 4 Oct 2017 16:25, "John Freeman" <notifications@github.com> wrote:

Wish I could use this at my company, but can't if it's GPL. Have you
considered a more permissive license, e.g. MIT?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/tools4j/groovy-tables/issues/3>, or mute the thread

**Comment by benjwarner** [comment]
Is now under MIT license.

**Comment by thejohnfreeman** [comment]
Awesome, thank you!

**Comment by thejohnfreeman** [comment]
One more ask (sorry!): Do you think you can release another version to Maven under this license?

**Comment by benjwarner** [comment]
Ah yes.  No probs.  Will release it in the next day or so.

**Comment by thejohnfreeman** [comment]
I know you're probably busy, but just wanted to leave a friendly reminder about this in case it slipped through the cracks. Thanks again!

**Comment by benjwarner** [comment]
Indeed, it did slip through the cracks :-)

I've just pushed out a new version1.5.

It usually takes up to 24 hours to appear in maven repos.  I'll keep my eye
on them to ensure it appears.

Cheers,
Ben

**Comment by benjwarner** [comment]
Hi John,
Thanks for you pull request, I forgot about the gradle file.

I've been trying to push a new build to maven repos.  But am getting some
unauthorized error.  It might be because I had a few failed connections
from here on the train.  Might have to wait until I'm home tonight.

Cheers,
Ben

**Comment by benjwarner** [comment]
Have release version 1.6.  Hopefully all good.
